language: php
php:
  - 7.2.5
env:
  global:
    secure: z3XRqfYkR1myI9c+ZCJiRFVTBrQigL1VgtXJhOhS1l26oihuVfQSeSJBXq8w6lcgsts4VxTmTkmuhEWCZTOy+ifgp3UCHZFOvf+J07QWcRFsRO+QVpq9/XooPbW/TAnVDzTMKgRtchj69fMbI4TQfiEXuKIkVQeXKHKv/Yu4Z1Cbr9cpvuENoW1M7Vraw2AEMcMfgZ9KmncIVYgb6pzypFE16nYV6pUstJDXn1AQbsGqnVJe78JQ+EB7TLFXG6dJI+HrPozLurHlPi5wO4ppuyNmhd3YjPjLJBhndcZ/6+LEEb8AVB+YXswSUW7JIH3rHsQXJ2WGO+9HMoWqTxTvidQZG7vI733kB/yP68f4jsubUPOFxJuMRWqizp7Ay7vNXvIxtOPdPoVDauH5htr+EEUS/Gi1ZzAn7KQOL0hXq0S4X+PwV5vaSWeFtIeuTpAenhCRlCd9U4O+HZ8JuG9Hwdo13bvfoqg4ZVBa6ghSOo8Qs8GtWoM6gAdJObl5tcwYSdu3PmsJBpFYQaJzbHjEha7q/LB2YmtlQ6XGdktBOdN9LxXOVOOITfN1+/C45ZKxmIp/U0lFm9NpHABQyDdDml9UP+C8vG1EsFCtBDk1SF0qAmbvNF6KfqvtBWS6rHRLUZ++TthgS/+95dNu69YtPodgl1ktbN2dpZ0FbFoC7FM=
before_script:
  - composer install --no-progress
script:
  - vendor/bin/couscous travis-auto-deploy
